### ISSUE TITLE
Android build one-to-one failed

### ISSUE THREAD

**Issue by GiacomoSilli** [opentok/one-to-one-sample-apps#153]
I'm getting the following error while building:

`Error:(33, 8) error: MainActivity is not abstract and does not override abstract method onCameraChanged(int) in Listener`

```
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

If i make "MainActivity" abstract, the response is that: 

```
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK META-INF/LICENSE
	File1: C:\Users\user\.gradle\caches\modules-2\files-2.1\org.codehaus.jackson\jackson-mapper-asl\1.9.13\1ee2f2bed0e5dd29d1cb155a166e6f8d50bbddb7\jackson-mapper-asl-1.9.13.jar
	File2: C:\Users\user\.gradle\caches\modules-2\files-2.1\org.codehaus.jackson\jackson-core-asl\1.9.13\3c304d70f42f832e0a86d45bd437f692129299a4\jackson-core-asl-1.9.13.jar
```

Any fix?

**Comment by marinaserranomontes** [comment]
hi @GiacomoSilli we have tested master/develop branches and these seem to be working.
Please note, the "onCameraChanged(int)" is an event from the OneToOneCommunicator listener, and it is implemented in the MainActivity.

Please, review the last week changes to be sure you are using the last code. Thanks!!

**Comment by GiacomoSilli** [comment]
Its strange, i have downloaded the code yesterday. I have to implement something or its a ready-to build code?

I'll try it again in some minuts

Thanks for answer

**Comment by marinaserranomontes** [comment]
Hi @GiacomoSilli 
It is a sample app, so, if you have downloaded it, you only need to setup the SESSIONID, TOKEN, APIKEY in the OpenTokConfig.java and run the app. 

Please, give us more details (logcat) about your error. Thanks!

**Comment by GiacomoSilli** [comment]
Solved by adding this in build.gradle:

```
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
        exclude 'META-INF/LGPL2.1'
        exclude 'META-INF/ASL2.0'
    }
}
```

Its working pretty good.
i'll try the one for iOS soon.

O.T. There is a sample/guide for One-To-Many app?

**Comment by marinaserranomontes** [comment]
@GiacomoSilli yes, you need to add in the build.gradle:     
packagingOptions {
        exclude 'META-INF/ASL2.0'
    } 
Thanks for feedback!! We are going to add to the doc/config
