### ISSUE TITLE
Video Freezes When First Party is on Firefox

### ISSUE THREAD

**Issue by rience** [opentok/one-to-one-sample-apps#157]
### General information

- Library version(s):Sample App Version 1.2
- iOS/Android/Browser version(s): JS
- Devices/Simulators/Machine affected: Firefox
- Reproducible in the demo project? (Yes/No): Yes 

## Bug report
I have tried sample project for simple video chat (two parties). However, in some cases - video published by Firefox (ver. 50.0.1) freezes.

#### Expected behavior
Video should not freeze.

#### Actual behavior
Video freezes

#### Steps to reproduce
1. Generate session and two tokens
2. Start Web server configured with token 1
3. Start another Web server configured with token 2 (for example on different port)
4. Open index.html on first server using Firefox and start publishing
5. Then open index.html on second server using browser on your choice and start publishing

Result: Stream from Firefox will freeze. On first windows - small window will be frozen on second browser - nothing will be seen coming from first browser.

Note: If you revert the case - first start publishing on any other browser than FF and then connect with FF - it'll be fine.

#### Crash log? Screenshots? Videos? Sample project?
Just follow the steps. I've cloned this repository and run using one liner HTTP server
```
 python -m SimpleHTTPServer 8000 # First server
 python -m SimpleHTTPServer 8001 # Second server
```

> ...

**Comment by adrice727** [comment]
@rience Are you using a Mac (OS X)?

**Comment by rience** [comment]
Yes. Indeed - I was using macOS. Thanks for that.

**Comment by Lucashuang0802** [comment]
Hi @rience, thanks so much for submitting this issue to raise attention. Looks like it's a bug from Firefox. The team has reported it. You can track it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1321853 😃
