### ISSUE TITLE
iOS pod install error: missing project file

### ISSUE THREAD

**Issue by GiacomoSilli** [opentok/one-to-one-sample-apps#163]
Hello,
When i run "pod install" from the root folder (one-to-one-sample-apps/iOS)
i get the following error:

`The plist file at path `/Users/****/Desktop/one-to-one-sample-apps-master/iOS/OneToOneSample.xcodeproj/project.pbxproj` doesn't exist.
`
How to solve that?

**Comment by GiacomoSilli** [comment]
It's working by using develop branch

**Comment by Lucashuang0802** [comment]
Hi @GiacomoSilli, thanks for submitting the issue. I believe the `master` and `develop` branch are out of sync. We will take a look and follow it up. Thanks for your support!

**Comment by Lucashuang0802** [comment]
@GiacomoSilli Appreciate your support. We have fixed the issue with a new project file from here: https://github.com/opentok/one-to-one-sample-apps/commit/4486d724e3438d5b6a3a7f0640652d573c532287
