### ISSUE TITLE
Android: How to re-initiate a Publisher session with same SessionID & Token.

### ISSUE THREAD

**Issue by sankar2389** [opentok/one-to-one-sample-apps#184]
As per our client need in mobile application the Publisher needs to initiate the session and show the text chat first and same as when a Subscriber joins the session, he starts with the text chat. If the subscriber wants to start & join video chat, he can ask the publisher and starts the video chat once publisher accepts & started.

Now the issue is if the Publisher initiates the session & press home button. App does not gets internet service, due to this the session disconnects after few auto reconnecting try outs. 
So we planned to re-initiate the same session with same session id & token, once the Publisher resumes the app. 
In this latest app we could not able to re-initiate the session. But in the previous example with the following package compile 'com.opentok.android:accelerator-pack:+' we can achieve connecting to session, But the text chat session is not connecting.

Please guide me. Thanks

**Comment by marinaserranomontes** [comment]
Hi @sankar2389 ,

Please note, the last sample using the accelerators code is here: https://github.com/opentok/accelerator-sample-apps-android

Regarding your comment, about how to pause and then, resume the session connection, I think you have several options:
- Pause/resume methods, where you are not going to disconnect from the session (you need to continue having network connection)
- Connect/Disconnect methods, where you are going to connect to the session and then, disconnect from the session.
Please note, in the current text-chat lib sample, we are passing the session object when we initialize them, so in the case you disconnect and connect, you will need to reinitialise the TextChatFragment as well.
The connectionID will be different.
https://github.com/opentok/accelerator-textchat-android/blob/master/textchat-acc-pack/src/main/java/com/tokbox/android/accpack/textchat/TextChatFragment.java#L123

**Comment by marinaserranomontes** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed.

Please reopen if you still encounter this issue You can also contribute directly to samples by providing a patch.

Thank you!
