### ISSUE TITLE
Error:Could not find any matches for com.opentok.android:opentok-accelerator-core:1.0.+ as no versions of com.opentok.android:opentok-accelerator-core are available. Required by:     project :app

### ISSUE THREAD

**Issue by ABhayBohra** [opentok/one-to-one-sample-apps#185]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/opentok/one-to-one-sample-apps/blob/master/README.md) 
- [ ] I have searched [existing issues](https://github.com/opentok/one-to-one-sample-apps/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by marinaserranomontes** [comment]
Hi @ABhayBohra ,

It should be working now. The URL changed temporary, but it was restored to the original URL: https://tokbox.bintray.com/maven/ some days ago.

Best,
Marina
